In [130]:
import pandas as pd
import os
from IPython.core.display import display, HTML

def multi_column_df_display(list_dfs, cols=3):
    html_table = "<table style='width:100%; border:0px'>{content}</table>"
    html_row = "<tr style='border:0px'>{content}</tr>"
    html_cell = "<td style='width:{width}%;vertical-align:top;border:0px'>{{content}}</td>"
    html_cell = html_cell.format(width=100/cols)

    cells = [ html_cell.format(content=df.to_html()) for df in list_dfs ]
    cells += (cols - (len(list_dfs)%cols)) * [html_cell.format(content="")] # pad
    rows = [ html_row.format(content="".join(cells[i:i+cols])) for i in range(0,len(cells),cols)]
    display(HTML(html_table.format(content="".join(rows))))

csv_path = '/home/thiagodepaulo/exp/PyPBG/exp/results/CSTR/'
l = []
for filename in os.listdir(csv_path):    
    if filename.endswith('.csv'):        
        df = pd.read_csv(csv_path+filename, index_col=0, header=0)
        s = filename.replace('.csv','').split('_')
        df['num_samples'] = int(s[1])
        df['num_exp'] = int(s[2])
        df['cls_name'] = df.index[1]
        l.append(df)
df = pd.concat(l)

In [131]:
df

,precision,recall,f1-score,support,id,num_samples,num_exp,cls_name
others,0.73,0.89,0.80,171.0,0,30,2,ArtificiallIntelligence
ArtificiallIntelligence,0.69,0.41,0.51,98.0,0,30,2,ArtificiallIntelligence
accuracy,0.00,0.00,0.72,269.0,0,30,2,ArtificiallIntelligence
macro,0.71,0.65,0.66,269.0,0,30,2,ArtificiallIntelligence
weighted,0.71,0.72,0.70,269.0,0,30,2,ArtificiallIntelligence
...,...,...,...,...,...,...,...,...
others,0.78,0.90,0.84,199.0,48,1,3,Robotics
Robotics,0.71,0.47,0.57,99.0,48,1,3,Robotics
accuracy,0.00,0.00,0.76,298.0,48,1,3,Robotics
macro,0.74,0.69,0.70,298.0,48,1,3,Robotics
weighted,0.75,0.76,0.75,298.0,48,1,3,Robotics

In [132]:
def f(x):
    return pd.Series(dict(precision = x['precision'].max(), 
                        recall = x['recall'].max(),   
                        f1_score = x['f1-score'].max(),                      
                        cls_name = set(x['cls_name'])))
df_acc = df.loc[['accuracy']].groupby(['num_samples', 'num_exp']).apply(f)
df_macro = df.loc[['macro']].groupby(['num_samples', 'num_exp']).apply(f)
df_w = df.loc[['weighted']].groupby(['num_samples', 'num_exp']).apply(f)

In [133]:
print("\t\t\t\t\tAs tabelas são respectivamente Accuracy, Macro e Weighted")
multi_column_df_display([df_acc, df_macro, df_w], cols=3)

					As tabelas são respectivamente Accuracy, Macro e Weighted

In [134]:
df_acc.groupby('num_samples').mean()

             precision  recall  f1_score
num_samples
1                  0.0     0.0     0.766
5                  0.0     0.0     0.788
10                 0.0     0.0     0.823
20                 0.0     0.0     0.841
30                 0.0     0.0     0.809

In [135]:
df_macro.groupby('num_samples').mean()

             precision  recall  f1_score
num_samples
1                0.708   0.739     0.708
5                0.678   0.754     0.675
10               0.680   0.792     0.689
20               0.677   0.805     0.687
30               0.707   0.719     0.698

In [136]:
df_w.groupby('num_samples').mean()

             precision  recall  f1_score
num_samples
1                0.770   0.766     0.761
5                0.844   0.788     0.802
10               0.889   0.823     0.847
20               0.902   0.841     0.866
30               0.834   0.809     0.815